# name: Outputs 

# on: push 

# jobs:
#   outputs-demo:
#     runs-on: ubuntu-latest
#     steps:
#       - name: "Getting Input"
#         id: step1
#         run: echo "version=1.0.1" > $GITHUB_OUTPUT
#       - name: "Getting Output"
#         run: echo "Version is " ${{ steps.step1.outputs.version }}

name: Outputs

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.step1.outputs.version }}
    steps:
      - name: "Build Step"
        id: step1
        run: echo "version=1.0.1" >> $GITHUB_OUTPUT
    
  deploy:
    runs-on: ubuntu-latest 
    needs: build 
    steps:
      - name: "Deployment Step"
        run: echo "The version is "${{ needs.build.outputs.ver }}
